### ISSUE TITLE
fromdict: primary key check should be after exclude check

### ISSUE THREAD

**Issue by gaaf** [danielholmstrom/dictalchemy#5]
The test for primary keys update is now done as first test. So even if the primary key fields are in the exclude list, an exception is raised. To circumvent, one needs to set allow_pk to True as well as put the primary key fields in the exclude list. Especially in the case of multi-column primary keys, this is error-prone. If one forgets (or makes a typo in) one primary key field in the exclude list, the allow_pk=True setting will allow an update. IMHO it would be more sensible to first check the exclude list and only if a field survives that, do the primary key check. In that case, allow_pk can be left False so mistakes in the exclude list are still caught.

This now fails while IMHO it should succeed:
```
h = Named('a name')
h.fromdict({'id': 12345}, exclude=['id'])
```
This currently succeeds:
```
h = Named('a name')
h.fromdict({'id': 12345}, allow_pk=True, exclude=['id'])
```

**Comment by danielholmstrom** [comment]
Not much is happening with dictalchemy so I simply released a new version 0.1.2.7 with a fix for this behaviour.
